services:
  fak-rest:
    image: dynamicsamic/todo_list:latest
    command: "uv run uvicorn src.restapi.app:app"
    depends_on:
      - fak-db
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    environment:
      - DB_USER=test_user
      - DB_PASWD=test_pswd
      - DB_NAME=test_db
      - DB_HOST=test_aidkit
      - DB_PORT=5432

  fak-db:
    image: postgres:16
    container_name: fak_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pswd
      - POSTGRES_DB=template1
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d test_db -U test_user"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: